### ISSUE TITLE
FEATURE REQUEST: screenshot upon install failure saved along with gist

### ISSUE THREAD

**Issue by bcurran3** [chocolatey-community/chocolatey-test-environment#36]
I've bumped into:

> 2019-03-07 01:49:44,741 2536 [WARN ] - Chocolatey timed out waiting for the command to finish. The timeout 
>  specified (or the default value) was '2700' seconds. Perhaps try a 
>  higher `--execution-timeout`? See `choco -h` for details.

...too numerous amount of times to mention.

A screenshot at that moment of failure would be immensely helpful to package maintainers who didn't expect a pop up request to install a dependency or a reboot request etc.

**Comment by bcurran3** [comment]
Of possible interest (though old):
https://github.com/igorsobreira/vagrant-screenshot

**Comment by ferventcoder** [comment]
This was opened on this repository - which is the test environment. The test environment has a GUI when it loads up and doesn't save any gists. Perhaps this was meant to go over to https://github.com/chocolatey/package-verifier/issues/55. I do see this is an older issue, so just now catching that.

**Comment by ferventcoder** [comment]
@gep13 close this issue as invalid please.
