### ISSUE TITLE
Adding Custom Chocolatey Installs to the script

### ISSUE THREAD

**Issue by cybrpimp** [chocolatey-community/chocolatey-test-environment#50]
I'm building our Windows VM off the script and help I have found but here but I'm not sure were I can add more chocolaty installs to our build.

Can someone please advise?

**Comment by gep13** [comment]
@cybrpimp I am not sure if I exactly follow what you are asking for.

Can you please provide more information about exactly what you are trying to do, and also how this relates to the chocolatey-test-environment.

**Comment by cybrpimp** [comment]
Yes, I'm trying to get a vagrant script setup that installed Chocolatey whic his why I used this script.

I'm also trying to get Chocolatey to install some packages like Notepad++ and others in the VM.

**Comment by gep13** [comment]
@cybrpimp this repository contains a vagrant file which is specifically intended for the testing of Chocolatey Packages, i.e. the expectation is that you will run `vagrant up` once, get everything installed, i.e. Chocolatey, and then take a snapshot of the VM.  Then you would update the installation scripts to include the packages that you want to test, and then you would run `vagrant provision` again, and then revert the snapshot once the testing is complete.

This likely isn't what you would want to be doing, but you can certainly use the base scripts included in this project to set up what you want.

What exactly isn't working for you, and what is it that you are trying.  Do you have a repository that you can point us at to take a look at?

**Comment by ferventcoder** [comment]
Closed due to staleness of this. It appears this was likely off topic
