### ISSUE TITLE
Clipto Pro 2.4.0 fails to install inside Chocolatey-test-environment

### ISSUE THREAD

**Issue by chtof** [chocolatey-community/chocolatey-test-environment#51]
It has worked wit Clipto Pro 2.2.2.

The same Chocolatey Package for Clipto Pro fails with the version 2.4.0 with the Chocolatey-Test-Environment but is successful on my Windows 10 computer:

**#### INSTALLED WITH CHOCOLATEY ####**
C:\Users\Administrator>cinst clipto-pro.install -pre --version=2.4.0
Chocolatey v0.10.15
Installing the following packages:
clipto-pro.install
By installing you accept licenses for the packages.
Progress: Downloading clipto-pro.install 2.4.0... 100%

clipto-pro.install v2.4.0 - Possibly broken
clipto-pro.install package files install completed. Performing other installatio
n steps.
Downloading clipto-pro.install
  from 'https://github.com/clipto-pro/Desktop/releases/download/v2.4.0/clipto.pr
o-2.4.0.exe'
Progress: 100% - Completed download of C:\Users\Administrator\AppData\Local\Temp
\1\chocolatey\clipto-pro.install\2.4.0\clipto.pro-2.4.0.exe (43.85 MB).
Download of clipto.pro-2.4.0.exe (43.85 MB) completed.
Hashes match.
Installing clipto-pro.install...
ERROR: Running ["C:\Users\Administrator\AppData\Local\Temp\1\chocolatey\clipto-p
ro.install\2.4.0\clipto.pro-2.4.0.exe" /S ] was not successful. Exit code was '-
1073741819'. See log for possible error messages.
The install of clipto-pro.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\clipto-pro.install\tools\choc
olateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - clipto-pro.install (exited -1073741819) - Error while running 'C:\ProgramData
\chocolatey\lib\clipto-pro.install\tools\chocolateyinstall.ps1'.
 See log for details.
**----> Result: Clipto is not installed.**

**#### INSTALLED OUTSIDE CHOCOLATEY ####**
C:\Users\Administrator>"C:\Users\Administrator\AppData\Local\Temp\1\chocolatey\c
lipto-pro.install\2.4.0\clipto.pro-2.4.0.exe" /S
**----> Result: Clipto is installed.**

**Comment by pauby** [comment]
I've manually installed the EXE and it works fine. The package also works fine.

Why do you consider the issue an issue with the test environment?

**Comment by chtof** [comment]
It worked outside Windows 2012R2.

But it's unbeliveable... The package failed during automated tests and also on my Chocolatey test environnement (crash window). I tested to submit a second time and the package has been validated.
The checksum was the same for all of thse tests. I have a doubt it will work again during a monthly check of the package.
By the software editor, I knew few hours ago version 2.2.2 of clipto-pro.install was build under windows and under Linux for the 2.4.0. It can be an explaination even if it is really strange.
So, I close for now.
