### ISSUE TITLE
[[ERROR] Vagrant failed to initialize at a very early stage:

### ISSUE THREAD

**Issue by bcurran3** [chocolatey-community/chocolatey-test-environment#54]
REF: https://gist.github.com/choco-bot/8a824109dec9a7e7664567efb2dd8f5f

[[ERROR] Vagrant failed to initialize at a very early stage:
[ERROR] The version of powershell currently installed on this host is less than
[ERROR] the required minimum version. Please upgrade the installed version of
[ERROR] powershell to the minimum required version and run the command again.
[ERROR]   Installed version: N/A
[ERROR]   Minimum required version: 3](url)

**Comment by gep13** [comment]
@bcurran3 thanks for taking the time to raise this issue.  This issue is not specific to this repository, but rather to the package-verifier repository.  I will move this over there.

**Comment by gep13** [comment]
@bcurran3 actually, I can't transfer an issue between GitHub Organisations.

Can I ask that you recreate this issue over there, and we can close this one out.

Thanks

**Comment by bcurran3** [comment]
Done
