### ISSUE TITLE
Vagrantfile no longer works with virtualbox

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey-community/chocolatey-test-environment#57]
Update to date clone, the vagrant file cannot find the virtualbox box to download

```
>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'chocolatey/test-environment' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'chocolatey/test-environment'
    default: URL: https://vagrantcloud.com/chocolatey/test-environment
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: chocolatey/test-environment
Address: https://vagrantcloud.com/chocolatey/test-environment
Requested provider: [:virtualbox]

```

It looks like only the hyper-v version has been released.

![image](https://user-images.githubusercontent.com/38865330/102249787-5c6d9980-3ec8-11eb-892f-7d0f77b4046a.png)

**Comment by gep13** [comment]
@TheCakeIsNaOH we recently pushed out a new VirtualBox image, so that the base image here matches what is used on the package-verifier instance. We updated the repo here to use that image, however, we then found a problem with the image. I think what you are seeing here is as a result of @pauby re-uploading the image to vagrant cloud.  I would suggest checking back in a little while and hopefully it will be there.

**Comment by pauby** [comment]
@TheCakeIsNaOH @gep13 A new Vagrant box for Virtualbox has been uploaded just now. Would appreciate any feedback.

**Comment by TheCakeIsNaOH** [comment]
@pauby It is working perfectly for me now. 

Thank you (and whoever else helped) for getting the box updated with the KBs. I am really glad that I won't have to sit through kb2919355 installing over and over while testing packages.

**Comment by gep13** [comment]
I have just taken this for a spin as well, (@TheCakeIsNaOH must have a better internet connection than I do 😄 ) and I can confirm that the issues that I saw with the last version have been addressed, and it is now working as expected.
