### ISSUE TITLE
Missing the Code of Conduct 

### ISSUE THREAD

**Issue by FahimFBA** [chocolatey-community/chocolatey-test-environment#65]
Hello, this project is currently missing the **Code of Conduct**. If you are interested in adding one, then please let me know so that I can add a PR for that. Also, in that case, I would also need an address (email address) for adding that in the Code of Conduct file.

**Comment by pauby** [comment]
Thanks for raising this and offering to raise a PR.

We are going to use the [Code Of Conduct (and others) from our Chocolatey organization](https://github.com/chocolatey/.github). We;'re in the process of doing that.
